name = "FiniteElements"
uuid = "68b98baf-bdce-4bdd-9257-74eaa3e5daef"
authors = ["PascalCr <64025214+PascalCr@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
